### ISSUE TITLE
Make the serial console printing work with the new packets

### ISSUE THREAD

**Issue by joshdboss** [EPFLRocketTeam/SupersonicTestRocket#12]
The new packet format is more versatile, although not yet compatible with the serial console printing.

**Comment by spacewolfXfr** [comment]
It should be OK for the sensors with wrappers. Testing is needed, as always.
 Some possible improvements:
- Add colors (define the color scheme to use)
- Add units (they are not always documented)

More general issue/question : `dataAcquisition` always does the setup and cleanup phase, but is called several time (at least once for `setup` in `main.cpp`, then in `loop`). Is this something which should be fixed ? (Split the function in `dataAcquisition_setup`, `..._core` and `..._cleanup` ?)

**Comment by spacewolfXfr** [comment]
Done here #50
